#!/usr/bin/perl

#   ENDIT - Efficient Northern Dcache Interface to TSM
#   Copyright (C) 2006-2021 Mattias Wadenstein <maswan@hpc2n.umu.se>
#   Copyright (C) 2018-2020 <Niklas.Edmundsson@hpc2n.umu.se>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.



# This is a drop-in replacement of "dsmc" that just moves the files
# to another location on the same host. Useful for small testing 
# deployments, CI/CD pipelines, etc - but probably not for anything
# useful with real data.
#
# This is simplistic and trusts input, if there is a line with something like
# $HOME/.ssh/id_rsa in the -filelist, expect it to be read/written/removed.
# Same goes for code execution. These side effects are unlikely if it is
# just used from the ENDIT daemons though.

use warnings;
use strict;

use POSIX qw(strftime);
use File::Temp qw /tempfile/;
use File::Basename;

# Add directory of script to module search path
use lib dirname (__FILE__);
use lib '/opt/endit';

use Endit qw(%conf readconf printlog);

###########
# Variables
$Endit::logsuffix = 'fake-dsmc.log';
# Location of the "tape library" root with asnode subdirs
my $archive = '/archive';

# Turn off output buffering
$| = 1;

readconf();

my $desclong="";
if($conf{'desc-long'}) {
	$desclong = " $conf{'desc-long'}";
}
printlog("$0: Starting$desclong...");

my $asnode = "default";
my $filelist = "";

if ($#ARGV < 1) {
	printlog "$#ARGV is too few arguments!";
	die "$#ARGV is too few arguments!";
}

my $arg;
foreach $arg (@ARGV) {
	$filelist = $1 if $arg =~ /-filelist=(.*)/;
	$asnode = $1 if $arg =~ /-asnode=(.*)/;
}

printlog "-filelist required" unless $filelist;
die "-filelist required" unless $filelist;
my $fl;
open($fl, "<", $filelist) or printlog "failed to open filelist $filelist: $!";

if ($ARGV[0] eq 'archive') {
	printlog "archiving from $filelist\n";
	while(<$fl>) {
		chomp;
		printlog `rsync --remove-source-files $_ $archive/$asnode/\n`;
	}
} elsif ($ARGV[0] eq 'retrieve') {
	my $indir = $conf{dir} . '/in/';
	printlog "retrieving from $filelist\n";
	while(<$fl>) {
		chomp;
		$_ =~ s/.*\//$archive\/$asnode\//;
		printlog `cp $_ $indir/\n`;
	}
} elsif ($ARGV[0] eq 'delete') {
	printlog "deleting from $filelist\n";
	while(<$fl>) {
		chomp;
		printlog "trying to delete $_\n";
		$_ =~ s/.*\//$archive\/$asnode\//;
		printlog "rm -v $_\n";
		printlog `rm -v $_`;
	}
} else {
	die "don't know how to $ARGV[0]!";
}
