#!/usr/bin/perl

#   ENDIT - Efficient Northern Dcache Interface to TSM
#   Copyright (C) 2026 <Niklas.Edmundsson@hpc2n.umu.se>
#   Copyright (C) 2006-2021 Mattias Wadenstein <maswan@hpc2n.umu.se>
#   Copyright (C) 2018-2020 <Niklas.Edmundsson@hpc2n.umu.se>
#
#   This program is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <http://www.gnu.org/licenses/>.



# This is a drop-in replacement of "dsmc" that just moves the files
# to another location on the same host. Useful for small testing 
# deployments, CI/CD pipelines, etc - but probably not for anything
# useful with real data.
#
# This is simplistic and trusts input, if there is a line with something like
# $HOME/.ssh/id_rsa in the -filelist, expect it to be read/written/removed.
# Same goes for code execution. These side effects are unlikely if it is
# just used from the ENDIT daemons though.
#
# Note that it doesn't try to emulate the dsmc output, just enough to trigger
# ENDIT daemon error handling.

use warnings;
use strict;

use File::Basename;

# Add directory where we expect to find our Endit module.
use lib dirname (__FILE__) . "/../";

use Endit qw(%conf readconf printlog);

###########
# Variables
$Endit::logname = 'emulate-dsmc';

# Turn off output buffering
$| = 1;

readconf();

my $desclong="";
if($conf{'desc-long'}) {
	$desclong = " $conf{'desc-long'}";
}
printlog("$0: Starting$desclong...");

# Try to send warn/die messages to log file
INIT {
        $SIG{__DIE__}=sub {
                printlog("DIE: $_[0]");
        };

        $SIG{__WARN__}=sub {
                print STDERR "$_[0]";
                printlog("WARN: $_[0]");
        };
}

if(! -d $conf{'emulate-dsmc_archivedir'}) {
	die "$0: emulate-dsmc_archivedir $conf{'emulate-dsmc_archivedir'}: $!";
}

if(system('rsync --version > /dev/null 2>&1')) {
	die "$0: rsync not found in path";
}

my $asnode = "default";
my $filelist = "";

if(scalar(@ARGV) < 2) {
	die "Usage: $0 archive|retrieve|delete -filelist=file [-asnode=name]";
}

foreach (@ARGV[ 1 .. $#ARGV ]) {
	if (/-filelist=(.*)/) {
		$filelist = $1;
	}
	elsif (/-asnode=(.*)/) {
		$asnode = $1;
	}
	else {
		warn "Argument $_ ignored";
	}
}

die "-filelist required" unless $filelist;
open(my $fl, "<", $filelist) or die "failed to open filelist $filelist: $!";

my @files = <$fl>;
close($fl) or warn "Closing $filelist: $!";
chomp @files;

my $exitcode = 0;

if ($ARGV[0] eq 'archive') {
	printlog "archiving from $filelist";
	foreach my $file (@files) {
		my $ret=`rsync --remove-source-files --bwlimit=$conf{'emulate-dsmc_bwlimit'} $file $conf{'emulate-dsmc_archivedir'}/$asnode/`;
		my $rc = $? >> 8;
		# Emulate dsmc error messages, ish.
		if($rc) {
			print "ANS9999E Unknown error, rsync code $rc output $ret for $file\n";
			$exitcode = 4;
		}
	}
} elsif ($ARGV[0] eq 'retrieve') {
	printlog "retrieving from $filelist";
	foreach my $file (@files) {
		my $archfile = $file;
		$archfile =~ s/.*\//$conf{'emulate-dsmc_archivedir'}\/$asnode\//;
		my $ret=`rsync --bwlimit=$conf{'emulate-dsmc_bwlimit'} $archfile $conf{dir_in}/`;
		my $rc = $? >> 8;
		# Emulate dsmc error messages, ish.
		if($rc == 23) {
			print "ANS1345E No objects on the server match '$file'\n";
			$exitcode = 4;
		}
		else {
			print "ANS9999E Unknown error, rsync code $rc output $ret for $file\n";
			$exitcode = 4;
		}
	}
} elsif ($ARGV[0] eq 'delete') {
	printlog "deleting from $filelist";
	foreach my $file (@files) {
		printlog "trying to delete $file";
		my $archfile = $file;
		$archfile =~ s/.*\//$conf{'emulate-dsmc_archivedir'}\/$asnode\//;
		unless( -f $archfile) {
			printlog "$file ($archfile) does not exist";
			print "ANS1345E No objects on the server match $file\n";
			$exitcode = 4;
			next;
		}
		if(unlink $archfile) {
			printlog "$file ($archfile) deleted";
		}
		else {
			warn "Deleting $file ($archfile) failed: $!";
			print "ANS9999E Delete $file failed: $!\n";
			$exitcode = 4;
		}
	}
} else {
	die "don't know how to $ARGV[0]!";
}

return $exitcode;
